# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protocol import gozo_pb2 as gozo__pb2


class SiameseStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
            '/Siamese/Predict',
            request_serializer=gozo__pb2.PredictRequest.SerializeToString,
            response_deserializer=gozo__pb2.PredictReply.FromString,
        )
        self.StoreFace = channel.unary_unary(
            '/Siamese/StoreFace',
            request_serializer=gozo__pb2.StoreFaceRequest.SerializeToString,
            response_deserializer=gozo__pb2.StoreFaceReply.FromString,
        )


class SiameseServicer(object):
    """The greeting service definition.
    """

    def Predict(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SiameseServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Predict': grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=gozo__pb2.PredictRequest.FromString,
            response_serializer=gozo__pb2.PredictReply.SerializeToString,
        ),
        'StoreFace': grpc.unary_unary_rpc_method_handler(
            servicer.StoreFace,
            request_deserializer=gozo__pb2.StoreFaceRequest.FromString,
            response_serializer=gozo__pb2.StoreFaceReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Siamese', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class Siamese(object):
    """The greeting service definition.
    """

    @staticmethod
    def Predict(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Siamese/Predict',
                                             gozo__pb2.PredictRequest.SerializeToString,
                                             gozo__pb2.PredictReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StoreFace(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Siamese/StoreFace',
                                             gozo__pb2.StoreFaceRequest.SerializeToString,
                                             gozo__pb2.StoreFaceReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
