# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gozo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngozo.proto\".\n\x10StoreFaceRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\"!\n\x0eStoreFaceReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0ePredictRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"\x1c\n\x0cPredictReply\x12\x0c\n\x04name\x18\x01 \x01(\t2i\n\x07Siamese\x12+\n\x07Predict\x12\x0f.PredictRequest\x1a\r.PredictReply\"\x00\x12\x31\n\tStoreFace\x12\x11.StoreFaceRequest\x1a\x0f.StoreFaceReply\"\x00\x42\x1fZ\x16gozo/classify/protocol\xa2\x02\x04Gozob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gozo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026gozo/classify/protocol\242\002\004Gozo'
  _STOREFACEREQUEST._serialized_start=14
  _STOREFACEREQUEST._serialized_end=60
  _STOREFACEREPLY._serialized_start=62
  _STOREFACEREPLY._serialized_end=95
  _PREDICTREQUEST._serialized_start=97
  _PREDICTREQUEST._serialized_end=127
  _PREDICTREPLY._serialized_start=129
  _PREDICTREPLY._serialized_end=157
  _SIAMESE._serialized_start=159
  _SIAMESE._serialized_end=264
# @@protoc_insertion_point(module_scope)
